### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by crefr** [Jepkins/Stack#1]
If stack.data = NULL, program finds error, but still ends with segmentation fault. Same while trying to use it after stack_dtor.
![изображение](https://github.com/user-attachments/assets/cdadb0a6-9d1a-4819-915b-f323949b424c)
![изображение](https://github.com/user-attachments/assets/da77572a-30b2-4675-8610-417bdb99231b)

**Comment by Jepkins** [comment]
This is intended problem, but it was supposed to happen only when u call destructor twice or before constructor. The thing is stack_assert calls destructor for the defective stack before finishing program. I thought this would be less obvious bug

**Comment by Jepkins** [comment]
Fixed in recent commit "dtor segfault"
