### ISSUE TITLE
little stack_dump issue

### ISSUE THREAD

**Issue by crefr** [Jepkins/Stack#3]
`stack_dump()` prints bytes like this (first element is 1, second is 2):
```
[0] = | 10 00 00 00 00 00 00 00 |
[1] = | 20 00 00 00 00 00 00 00 |
```
But both in little and big endians bits in byte are not reversed, so it must be like this:
```
[0] = | 01 00 00 00 00 00 00 00 |
[1] = | 02 00 00 00 00 00 00 00 |
```
So, in `stack_dump()` you can replace this:
```c
fprintf(stderr, "%.1X%.1X ", byte & 0x0f, (byte & 0xf0) >> 4);
```
to this:
```c
fprintf(stderr, "%02X ", byte);
```

**Comment by Jepkins** [comment]
Fixed. Thanks
